publisher: ee publisher
apiVersion: v2
name: ee name
version: latest
type: VS Code extension
displayName: ee displayName
title: ee title.
description: ee descriptiomn eee.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
category: Other
spec:
  extensions:
  - https://github.com/tomascechatbroadcomcom/che-devfile/releases/download/vEE_0.8.0/broadcomMFD.explorer-for-endevor-0.8.0.vsix
